[build]
functions = "./functions"

# [context.branch-deploy]
# command = "nuxt generate && rm -rf functions/ && netlify-lambda build lambda/ && cp netlify_headers dist/_headers"

[context.deploy-preview]
command = "nuxt generate && rm -rf functions/ && netlify-lambda build lambda/ && cp netlify_headers dist/_headers"
