backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
publish_mode: editorial_workflow
site_url: https://iyumusic.tokyo
display_url: https://iyumusic.tokyo

collections:
  - name: "live-info"
    label: "Live Info"
    folder: "_posts/live-info"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "イベント名"
        name: "title"
        widget: "string"
      - label: "公開日"
        name: "date"
        widget: "datetime"
      - label: "イベント日付"
        name: "date"
        widget: "datetime"
      - label: "場所"
        name: "place"
        widget: "string"
      - label: "チケット"
        name: "ticket"
        widget: "list"
        default: ["未定"]
        allow_add: false
        fields:
          - { label: "adv", name: "adv", widget: "number" }
          - { label: "door", name: "door", widget: "number" }
          - { label: "other", name: "other", widget: "string" }
      - label: "Open"
        name: "time_open"
        widget: "string"
        default: "未定"
      - label: "Start"
        name: "time_start"
        widget: "string"
        default: "未定"
      - label: "iyu出演予定時間"
        name: "iyu_appear_time"
        widget: "string"
      - label: "対バン"
        name: "with"
        widget: "list"
        default: ["未定"]
        field: { label: "band_name", name: "band_name", widget: "string" }
