backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
publish_mode: editorial_workflow
site_url: https://iyumusic.tokyo
display_url: https://iyumusic.tokyo
extension: json

collections:
  - name: "liveInfo"
    label: "Live Info"
    folder: "_posts/liveInfo"
    create: true
    identifier_field: "eventDate"
    slug: "{{slug}}"
    fields:
      - label: "イベント名"
        name: "title"
        widget: "string"
      - label: "公開日"
        name: "publishDate"
        widget: "datetime"
      - label: "イベント日付"
        name: "eventDate"
        widget: "date"
      - label: "場所"
        name: "place"
        widget: "string"

      - label: "チケット(予約)"
        name: "ticketAdv"
        widget: "number"
      - label: "チケット(当日)"
        name: "ticketDoor"
        widget: "number"
      - label: "チケット(その他ドリンクとか)"
        name: "ticketOther"
        widget: "string"

      - label: "Open"
        name: "timeOpen"
        widget: "datetime"
        format: 'HH:mm'
      - label: "Start"
        name: "timeStart"
        widget: "datetime"
        default: "未定"
        format: 'HH:mm'
      - label: "iyu出演時刻"
        name: "timeIyuAppear"
        widget: "datetime"
        format: 'HH:mm'
        required: false

      - label: "対バン"
        name: "with"
        widget: "list"
        field: { label: "bandName", name: "bandName", widget: "string" }
        required: false
