backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
publish_mode: editorial_workflow
site_url: https://iyumusic.tokyo
display_url: https://iyumusic.tokyo

collections:
  - name: "liveInfo"
    label: "Live Info"
    folder: "_posts/liveInfo"
    create: true
    identifier_field: "eventDate"
    slug: "{{slug}}"
    fields:
      - label: "イベント名"
        name: "title"
        widget: "string"
      - label: "公開日"
        name: "publishDate"
        widget: "datetime"
      - label: "イベント日付"
        name: "eventDate"
        widget: "datetime"
      - label: "場所"
        name: "place"
        widget: "string"
      - label: "チケット"
        name: "ticket"
        widget: "list"
        label_singular: '情報'
        allow_add: false
        fields:
          - { label: "adv", name: adv, widget: "number" }
          - { label: "door", name: door, widget: "number" }
          - { label: "other", name: other, widget: "string", required: false }

      # - label: "時間"
      #   name: "time"
      #   widget: "list"
      #   default: ["未定"]
      #   allow_add: false
      #   fields:
      #     - { label: "list", name: "adv", widget: "number" }
      #     - { label: "door", name: "door", widget: "number" }
      #     - { label: "other", name: "other", widget: "string", required: false }

      # format: 'YYYY-MM-DD HH:mm',

      # - label: "Open"
      #   name: "timeOpen"
      #   widget: "string"
      #   default: "未定"
      # - label: "Start"
      #   name: "time_start"
      #   widget: "string"
      #   default: "未定"
      # - label: "iyu出演予定時間"
      #   name: "iyu_appear_time"
      #   widget: "string"
      #   required: false

      - label: "対バン"
        name: "with"
        widget: "list"
        default: ["未定"]
        field: { label: "band_name", name: "band_name", widget: "string" }
